config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:index, :show]

  root "posts#home"

end

app/models/anchor.rb
class Anchor < ActiveRecord::Base
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :post
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :images, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json

  def home  

  end

  def index
    #@posts = Post.all
    @posts= Post.order("timestamp desc").paginate(:page => params[:page], :per_page => 30)
    @posts= @posts.where(bedrooms: params["bedrooms"]) if params["bedrooms"].present?
    @posts= @posts.where(bathrooms: params["bathrooms"]) if params["bathrooms"].present?
    @posts= @posts.where(neighborhood: params["neighborhood"]) if params["neighborhood"].present?
    @posts= @posts.where("price > ?", params["min_price"]) if params["price"].present?
    @posts= @posts.where("price < ?", params["max_price"]) if params["price"].present?
    @posts= @posts.where("sqft > ?", params["sqft"]) if params["sqft"].present?
    @posts= @posts.where("sqft < ?", params["sqft"]) if params["sqft"].present?
    @posts= @posts.where(cats: params["cats"]) if params["cats"].present?
    @posts= @posts.where(dogs: params["dogs"]) if params["dogs"].present?
    @posts= @posts.where(w_d_in_unit: params["w_d_in_unit"]) if params["w_d_in_unit"].present?
    @posts= @posts.where(street_parking: params["street_parking"]) if params["street_parking"].present?
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @images= @post.images
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:heading, :body, :price, :neighborhood, :external_url, :timestamp)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Real Estate</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_filter.html.erb
<div class="filter">
  <%= form_tag posts_path, method: :get, class: "form-inline" do %>
  
    <div class="row">
      <div class="col-md-4">
        <%= label_tag "Price" %>
      </div>
      <div class="col-md-2">
        <%= label_tag :bedrooms %>
      </div>
      <div class="col-md-2">
        <%= label_tag :bathrooms %>
      </div>
      <div class="col-md-4">
        <%= label_tag :neighborhood %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-4">
        <%= text_field_tag :min_price, params[:min_price], placeholder: "minimum", class: "form-control input-sm" %>
        <%= text_field_tag :max_price, params[:max_price], placeholder: "maximum", class: "form-control input-sm" %>
      </div>
      <div class="col-md-2">
        <%= text_field_tag :bedrooms, params[:bedrooms], placeholder: "# of beds", class: "form-control input-sm" %>
      </div>
      <div class="col-md-2">
        <%= text_field_tag :bathrooms, params[:bathrooms], placeholder: "# of baths", class: "form-control input-sm" %>
      </div>
      <div class="col-md-4">
        <%= select_tag(:neighborhood, options_from_collection_for_select(Location.all, :name, :name, params[:neighborhood]), { include_blank: true, class: "form-control input-sm" }) %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-4">
        <%= label_tag "Square Footage" %>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-4">
        <%= text_field_tag :min_sqft, params[:min_sqft], placeholder: "minimum", class: "form-control input-sm" %>
        <%= text_field_tag :max_sqft, params[:max_sqft], placeholder: "maximum", class: "form-control input-sm" %>
      </div>
      <div class="col-md-1">
        <%= label_tag :cats %>
        <%= check_box_tag :cats, "YES", params[:cats] %>
      </div>
      <div class="col-md-1">
        <%= label_tag :dogs %>
        <%= check_box_tag :dogs, "YES", params[:dogs] %>
      </div>
      <div class="col-md-2">
        <%= label_tag "Washer/dryer in unit" %>
        <%= check_box_tag :w_d_in_unit, "YES", params[:w_d_in_unit] %>
      </div>
      <div class="col-md-4">
        <%= label_tag :street_parking %>
        <%= check_box_tag :street_parking, "YES", params[:street_parking] %>
        <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
      </div>
    </div>  

  <% end %>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :heading %><br>
    <%= f.text_field :heading %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :bathroom %><br>
    <%= f.text_field :bathroom %>
  </div>
  <div class="field">
    <%= f.label :bedroom %><br>
    <%= f.text_field :bedroom %>
  </div>
  <div class="field">
    <%= f.label :cat %><br>
    <%= f.text_field :cat %>
  </div>
  <div class="field">
    <%= f.label :dogs %><br>
    <%= f.text_field :dogs %>
  </div>
  <div class="field">
    <%= f.label :w_d_in_unit %><br>
    <%= f.text_field :w_d_in_unit %>
  </div>
  <div class="field">
    <%= f.label :street_parking %><br>
    <%= f.text_field :street_parking %>
  <div class="field">
    <%= f.label :neighborhood %><br>
    <%= f.text_field :neighborhood %>
  </div>
  <div class="field">
    <%= f.label :timestamp %><br>
    <%= f.text_field :timestamp %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/home.html.erb
<div class="jumbotron">
  <div class="background-image"></div>
  <div class="container">
  	<div class="center">
	    <h1>Real Estate</h1>
    	<h2>The Easiest Way to Find Apartment Rentals in Myanmar</h2>

	    <%= render 'filter' %>
  	</div>
  </div>
</div>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <%= render 'filter' %>
   <% if @posts.empty? %>
   <hr>
   <h3>No results found</h3>
 <% else %>
   <table class="table tablehover tablecondensed">
     <thead>
       <tr>
         <th class="center">Preview</th>
         <th class="center">Heading</th>
         <th class="center">Price</th>
         <th class="center">baths</th>
         <th class="center">beds</th>
         <th class="center">Neighborhood</th>
         <th class="center">Timestamp</th> 
         <!-- 
         <th class="center">Sqft</th>
         <th class="center">Cats</th>
         <th class="center">Dogs</th>
         <th class="center">w_d_in_unit</th>
         <th class="center">Parking</th>
       -->
       </tr>
     </thead>
     <tbody>

       <% @posts.each do |post| %>

         <tr>
           <td width="13%" height="120px">
            <% if post.images.empty? %>
              <%= image_tag 'https://s3-ap-southeast-1.amazonaws.com/craigslist-scraper/images/no-photo-available.jpg', class: "thumbnail" %>
            <% else %>
              <%= image_tag post.images.first.url   , class: "thumbnail" %>
            <% end %> 
           </td>
           <td style="vertical-align:middle"><%= link_to post.heading, post %></td>
           <td class="center" style="vertical-align:middle"><%= number_to_currency(post.price, precision: 0) %></td>
           <td class="center" style="vertical-align:middle"><%= post.bedrooms %></td>
           <td class="center" style="vertical-align:middle"><%= post.bathrooms %></td>
           <td class="center" style="vertical-align:middle"><%= post.neighborhood %></td>
           <td class="center" style="vertical-align:middle"><%= "#{time_ago_in_words(Time.at(post.timestamp.to_i))} ago" %></td>
           <!-- <td class="center"><%= post.sqft %></td>
           <td class="center"><%= post.cats %></td>
           <td class="center"><%= post.dogs %></td>
           <td class="center"><%= post.w_d_in_unit %></td>
           <td class="center"><%= post.street_parking %></td>
           <td class="center"><%# link_to 'Show', post %></td>
           <td class="center"><%# link_to 'Edit', edit_post_path(post) %></td>
           <td class="center"><%# link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
         </tr>
       <% end %>
     </tbody>
   </table>

   <%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
 <% end %>
 </div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="header">
    <p>
      <h3><%= @post.heading %></h3>
    </p>

    <p>
      <strong>External url:</strong>
      <%= @post.external_url %>
    </p>
  </div>
  <div class="row">
    <div class="col-md-7" id="post-images">
      <% if @images.blank? %>
        <%= image_tag 'https://s3-ap-southeast-1.amazonaws.com/craigslist-scraper/images/no-photo-available.jpg', class: "thumbnail"%>
      <% else %>
        <% @images.each do |image| %>
          <%= image_tag image.url, class: "thumbnail"%>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-5">
      <div class="basic-info">
        <h4>Basic Info</h4>
        Price: <%= number_to_currency(@post.price, precision: 0) %><br />
        Last Updated<%= "#{time_ago_in_words(Time.at(@post.timestamp.to_i))} ago" %><br />
        <% if @post.neighborhood.present? %>
          <%= @post.neighborhood %><br />
        <% end %>

        <% if @post.bedrooms.present? %>
          Bedrooms: <%= @post.bedrooms %><br />
        <% end %>

        <% if @post.bathrooms.present? %>
          Bathrooms: <%= @post.bathrooms %><br />
        <% end %>

        <% if @post.sqft.present? %>
          Square Footage: <%= @post.sqft %>
        <% end %>

        <% if @post.cats.present? %>
          Cats: <%= @post.cats %>
        <% end %>

        <% if @post.dogs.present? %>
          Dogs: <%= @post.dogs %>
        <% end %>

        <% if @post.w_d_in_unit.present? %>
          <%= @post.w_d_in_unit %>
        <% end %>

        <% if @post.street_parking.present? %>
          <%= @post.street_parking %>
        <% end %>

      </div>  
      <div class="description">
        <h5><%= @post.body %></h5>
      </div>
    </div>
  </div>
</div>